# Generated by Django 6.0.7 on 2026-07-17 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_inscricao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
